### ISSUE TITLE
sitemap does not return all subreddits

### ISSUE THREAD

**Issue by anvaka** [reddit/reddit#1610]
If I download sitemap: https://www.reddit.com/sitemap I get only small chunk of subreddits. https://www.reddit.com/subreddit_sitemap?index=0 returns only 50k links, popular subreddits are missing. Seting index to `1` or any other number returns `404`

It would be nice to get all subreddits from the sitemap.

**Comment by telaviv** [comment]
Hey @anvaka! This is actually coming! The reason we did this for the moment is because we are running an experiment to see how our SEO is affected. You can see the details here:

https://github.com/reddit/reddit/blob/master/r2/r2/lib/sitemaps/data.py#L51

**Comment by telaviv** [comment]
This was fixed by 7edd1ec8cd147ba0f71fa9ceaf45706fc869a3ca

**Comment by anvaka** [comment]
This is fantastic. Thank you!

**Comment by anvaka** [comment]
I think it's still does not return all subreddits correctly. Try this:

```
curl --silent http://reddit-sitemaps.s3-website-us-east-1.amazonaws.com/subreddit_sitemap/{0..12}.xml | zgrep -noi https://www.reddit.com/r/videos/
```

This will give `0` results, though `/r/videos/` should be in response. 

Note, I tried the command above on a subreddit which is present in the sitemap, and I get correct results:

```
curl --silent http://reddit-sitemaps.s3-website-us-east-1.amazonaws.com/subreddit_sitemap/{0..12}.xml | zgrep -noi https://www.reddit.com/r/beesto
4:https://www.reddit.com/r/Beesto
13:https://www.reddit.com/r/beesto
```

**Comment by telaviv** [comment]
Nice find @anvaka! 

@jophuds do you have any idea why /r/videos would be missing from the list?

**Comment by telaviv** [comment]
@anvaka this should be fixed now. Please let us know if you find anything else out of the ordinary!

**Comment by anvaka** [comment]
Thanks! I see /r/videos now and will check the remaining.

I noticed that http://reddit-sitemaps.s3-website-us-east-1.amazonaws.com/subreddit-sitemaps.xml has a link to `http://reddit-sitemaps.s3-website-us-east-1.amazonaws.com/subreddit_sitemap/` which give `404`
